// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v4.25.3
// source: statistics_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTopPostsRequest_SortType int32

const (
	GetTopPostsRequest_Likes GetTopPostsRequest_SortType = 0
	GetTopPostsRequest_Views GetTopPostsRequest_SortType = 1
)

// Enum value maps for GetTopPostsRequest_SortType.
var (
	GetTopPostsRequest_SortType_name = map[int32]string{
		0: "Likes",
		1: "Views",
	}
	GetTopPostsRequest_SortType_value = map[string]int32{
		"Likes": 0,
		"Views": 1,
	}
)

func (x GetTopPostsRequest_SortType) Enum() *GetTopPostsRequest_SortType {
	p := new(GetTopPostsRequest_SortType)
	*p = x
	return p
}

func (x GetTopPostsRequest_SortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetTopPostsRequest_SortType) Descriptor() protoreflect.EnumDescriptor {
	return file_statistics_service_proto_enumTypes[0].Descriptor()
}

func (GetTopPostsRequest_SortType) Type() protoreflect.EnumType {
	return &file_statistics_service_proto_enumTypes[0]
}

func (x GetTopPostsRequest_SortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetTopPostsRequest_SortType.Descriptor instead.
func (GetTopPostsRequest_SortType) EnumDescriptor() ([]byte, []int) {
	return file_statistics_service_proto_rawDescGZIP(), []int{2, 0}
}

type GetPostStatisticsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId uint64 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
}

func (x *GetPostStatisticsRequest) Reset() {
	*x = GetPostStatisticsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statistics_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPostStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostStatisticsRequest) ProtoMessage() {}

func (x *GetPostStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetPostStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostStatisticsRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetPostStatisticsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId uint64 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Likes  uint64 `protobuf:"varint,2,opt,name=Likes,proto3" json:"Likes,omitempty"`
	Views  uint64 `protobuf:"varint,3,opt,name=Views,proto3" json:"Views,omitempty"`
}

func (x *GetPostStatisticsResponse) Reset() {
	*x = GetPostStatisticsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statistics_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPostStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostStatisticsResponse) ProtoMessage() {}

func (x *GetPostStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetPostStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostStatisticsResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetPostStatisticsResponse) GetLikes() uint64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *GetPostStatisticsResponse) GetViews() uint64 {
	if x != nil {
		return x.Views
	}
	return 0
}

type GetTopPostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderBy GetTopPostsRequest_SortType `protobuf:"varint,1,opt,name=OrderBy,proto3,enum=GetTopPostsRequest_SortType" json:"OrderBy,omitempty"`
}

func (x *GetTopPostsRequest) Reset() {
	*x = GetTopPostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statistics_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPostsRequest) ProtoMessage() {}

func (x *GetTopPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPostsRequest.ProtoReflect.Descriptor instead.
func (*GetTopPostsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopPostsRequest) GetOrderBy() GetTopPostsRequest_SortType {
	if x != nil {
		return x.OrderBy
	}
	return GetTopPostsRequest_Likes
}

type GetTopPostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Posts []*GetTopPostsResponse_Post `protobuf:"bytes,1,rep,name=Posts,proto3" json:"Posts,omitempty"`
}

func (x *GetTopPostsResponse) Reset() {
	*x = GetTopPostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statistics_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPostsResponse) ProtoMessage() {}

func (x *GetTopPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPostsResponse.ProtoReflect.Descriptor instead.
func (*GetTopPostsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopPostsResponse) GetPosts() []*GetTopPostsResponse_Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type GetTopUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*GetTopUsersResponse_User `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
}

func (x *GetTopUsersResponse) Reset() {
	*x = GetTopUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statistics_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsersResponse) ProtoMessage() {}

func (x *GetTopUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsersResponse.ProtoReflect.Descriptor instead.
func (*GetTopUsersResponse) Descriptor() ([]byte, []int) {
	return file_statistics_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTopUsersResponse) GetUsers() []*GetTopUsersResponse_User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetTopPostsResponse_Post struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Author     string `protobuf:"bytes,2,opt,name=Author,proto3" json:"Author,omitempty"`
	Statistics uint64 `protobuf:"varint,3,opt,name=Statistics,proto3" json:"Statistics,omitempty"`
}

func (x *GetTopPostsResponse_Post) Reset() {
	*x = GetTopPostsResponse_Post{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statistics_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopPostsResponse_Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPostsResponse_Post) ProtoMessage() {}

func (x *GetTopPostsResponse_Post) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPostsResponse_Post.ProtoReflect.Descriptor instead.
func (*GetTopPostsResponse_Post) Descriptor() ([]byte, []int) {
	return file_statistics_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetTopPostsResponse_Post) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTopPostsResponse_Post) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *GetTopPostsResponse_Post) GetStatistics() uint64 {
	if x != nil {
		return x.Statistics
	}
	return 0
}

type GetTopUsersResponse_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Likes    uint64 `protobuf:"varint,2,opt,name=Likes,proto3" json:"Likes,omitempty"`
}

func (x *GetTopUsersResponse_User) Reset() {
	*x = GetTopUsersResponse_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statistics_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopUsersResponse_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsersResponse_User) ProtoMessage() {}

func (x *GetTopUsersResponse_User) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsersResponse_User.ProtoReflect.Descriptor instead.
func (*GetTopUsersResponse_User) Descriptor() ([]byte, []int) {
	return file_statistics_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetTopUsersResponse_User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetTopUsersResponse_User) GetLikes() uint64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

var File_statistics_service_proto protoreflect.FileDescriptor

var file_statistics_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x50, 0x6f,
	0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x69, 0x65, 0x77, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x56, 0x69, 0x65, 0x77, 0x73, 0x22, 0x6e, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x22, 0x20, 0x0a, 0x08, 0x53, 0x6f,
	0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x69, 0x65, 0x77, 0x73, 0x10, 0x01, 0x22, 0x96, 0x01, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x05,
	0x50, 0x6f, 0x73, 0x74, 0x73, 0x1a, 0x4e, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a,
	0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x38,
	0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x32, 0xd6, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x12, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_statistics_service_proto_rawDescOnce sync.Once
	file_statistics_service_proto_rawDescData = file_statistics_service_proto_rawDesc
)

func file_statistics_service_proto_rawDescGZIP() []byte {
	file_statistics_service_proto_rawDescOnce.Do(func() {
		file_statistics_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_statistics_service_proto_rawDescData)
	})
	return file_statistics_service_proto_rawDescData
}

var file_statistics_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_statistics_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_statistics_service_proto_goTypes = []interface{}{
	(GetTopPostsRequest_SortType)(0),  // 0: GetTopPostsRequest.SortType
	(*GetPostStatisticsRequest)(nil),  // 1: GetPostStatisticsRequest
	(*GetPostStatisticsResponse)(nil), // 2: GetPostStatisticsResponse
	(*GetTopPostsRequest)(nil),        // 3: GetTopPostsRequest
	(*GetTopPostsResponse)(nil),       // 4: GetTopPostsResponse
	(*GetTopUsersResponse)(nil),       // 5: GetTopUsersResponse
	(*GetTopPostsResponse_Post)(nil),  // 6: GetTopPostsResponse.Post
	(*GetTopUsersResponse_User)(nil),  // 7: GetTopUsersResponse.User
	(*emptypb.Empty)(nil),             // 8: google.protobuf.Empty
}
var file_statistics_service_proto_depIdxs = []int32{
	0, // 0: GetTopPostsRequest.OrderBy:type_name -> GetTopPostsRequest.SortType
	6, // 1: GetTopPostsResponse.Posts:type_name -> GetTopPostsResponse.Post
	7, // 2: GetTopUsersResponse.Users:type_name -> GetTopUsersResponse.User
	1, // 3: StatisticsService.GetPostStatistics:input_type -> GetPostStatisticsRequest
	3, // 4: StatisticsService.GetTopPosts:input_type -> GetTopPostsRequest
	8, // 5: StatisticsService.GetTopUsers:input_type -> google.protobuf.Empty
	2, // 6: StatisticsService.GetPostStatistics:output_type -> GetPostStatisticsResponse
	4, // 7: StatisticsService.GetTopPosts:output_type -> GetTopPostsResponse
	5, // 8: StatisticsService.GetTopUsers:output_type -> GetTopUsersResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_statistics_service_proto_init() }
func file_statistics_service_proto_init() {
	if File_statistics_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_statistics_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPostStatisticsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_statistics_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPostStatisticsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_statistics_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopPostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_statistics_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopPostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_statistics_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_statistics_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopPostsResponse_Post); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_statistics_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopUsersResponse_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_statistics_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statistics_service_proto_goTypes,
		DependencyIndexes: file_statistics_service_proto_depIdxs,
		EnumInfos:         file_statistics_service_proto_enumTypes,
		MessageInfos:      file_statistics_service_proto_msgTypes,
	}.Build()
	File_statistics_service_proto = out.File
	file_statistics_service_proto_rawDesc = nil
	file_statistics_service_proto_goTypes = nil
	file_statistics_service_proto_depIdxs = nil
}
