services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432

  user_service:
    build: ./user_service
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./user_service/signature.pem:/tmp/signature.pem
      - ./user_service/signature.pub:/tmp/signature.pub
    command: [
        "--private", "/tmp/signature.pem",
        "--public", "/tmp/signature.pub",
        "--port", "8080",
        "--db-host", "db",
        "--db-port", "5432",
        "--db-username", "postgres",
        "--db-password", "pass",
        "--db-name", "postgresdb",
      ]
