services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  statistics_db:
    image: yandex/clickhouse-server:latest
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8123:8123

  statistics_service:
    build: ./statistics_service
    restart: unless-stopped
    depends_on:
      - kafka
      - statistics_db
    ports:
      - 8100:8100
    command: [
        "--http-port", "8100",
        "--grpc-port", "8200",
        "--db-address", "http://statistics_db:8123?debug=true",
        "--db-name", "statisticsdb",
        "--kafka-url", "kafka:9092",
      ]

  post_db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postdb
    ports:
      - 5433:5432

  post_service:
    build: ./post_service
    restart: unless-stopped
    depends_on:
      - post_db
    ports:
      - 8090:8090
    command: [
        "--port", "8090",
        "--db-host", "post_db",
        "--db-port", "5432",
        "--db-username", "postgres",
        "--db-password", "pass",
        "--db-name", "postdb",
      ]

  user_db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: userdb
    ports:
      - 5432:5432

  user_service:
    build: ./user_service
    restart: unless-stopped
    depends_on:
      - kafka
      - user_db
      - post_service
      - statistics_service
    ports:
      - 8080:8080
    volumes:
      - ./user_service/signature.pem:/tmp/signature.pem
      - ./user_service/signature.pub:/tmp/signature.pub
    command: [
        "--private", "/tmp/signature.pem",
        "--public", "/tmp/signature.pub",
        "--port", "8080",
        "--db-host", "user_db",
        "--db-port", "5432",
        "--db-username", "postgres",
        "--db-password", "pass",
        "--db-name", "userdb",
        "--post-server-addr", "post_service:8090",
        "--kafka-url", "kafka:9092",
        "--statistics-server-addr", "statistics_service:8200"
      ]
